#设置列表
slot-list:
  #id随意
  示范例子:
    #需要映射的槽位
    #格式 模式<->槽位
    #模式有两种
    #vanilla 原版槽位
    #core 龙核槽位
    mapped: 'vanilla<->0'
    #映射到的槽位
    mapping: 'core<->额外槽位5'
    #用于识别的lore
    lores:
      - ' '
      - '&6该物品为特殊物品, 仅用于展示'

#开启后点击原版槽位
#会往后台发送数字id
debug: false

#语言设置
message:
  #前缀
  prefix: '&7[&cDragonAttackSlot&7] '
  #插件帮助
  help:
    - '&7[&cDragonAttackSlot&7] &6插件帮助'
    - '&f/dragonattackslot|das help|h &e查看帮助'
    - '&f/dragonattackslot|das clear|c 玩家 &e清除玩家身上的违规物品'
    - '&f/dragonattackslot|das reload|r &e重载插件'
    - '&b| 符号用于分割全称与简称'
  #无法拿起物品
  cant-take: '&4你无法拿取此物品'
  #无法切换到物品
  cant-swap: '&4你无法切换到此物品栏'
  #无法丢弃物品
  cant-drop: '&4你无法丢弃此物品'
  #无法快速移动物品
  cant-fast-move: '&4你无法快速移动物品'
  #无法切换副手
  cant-swap-hand: '&4你无法切换此物品到主副手'
  #物品获取失败
  get-item-error: '&4物品获取失败, 请检查配置是否出错'
  #身上存在违规物品:
  have-error-item: '&4身上存在违规物品, 已清除'
  #只允许左键点击
  must-left-click: '&4只允许通过左键点击映射物品'
  #插件配置错误
  config-error: '&4插件配置错误, 请检查配置'
  #玩家离线
  player-not-online: '&4玩家处于离线状态'
  #开启debug后点击背包原版槽位
  debug-format: '&6你点击了&f: &b<id>'
  #重载插件
  reload: '&a插件重载完成'
